[font]
size = 12.0

[font.bold]
family = "Deja Vu Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Deja Vu Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Deja Vu Sans Mono"
style = "Italic"

[font.normal]
family = "Deja Vu Sans Mono"
style = "Regular"

# Colors (Everforest Dark)

# Default colors
[colors.primary]
background = '#2D353d'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

# Bright colors
[colors.bright]
black = '#475258'
red = '#e67e80'
green = '#a7c080'
yellow = '#dbbc7f'
blue = '#7fbbb3'
magenta = '#d699b6'
cyan = '#83c092'
white = '#d3c6aa'

[window]
  padding = { x = 2, y = 2}
	opacity = 0.9
